Closes #982: Avoid crash when writing PNG file using Python 3.
binascii.crc32() has changed in version 3.0.
In Py2 it returns value in the range [-2**31, 2**31-1],
in Py3 in [0, 2**32-1].

This change made write_png_depth() crash with:
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

--HG--
branch : stable